Repository benchttp/desktop, pull requests merged in 2022-09, with the labels that each got.

#14 feat: use free port
  .env.development
  scripts/sidecar-exec.sh
  src/App.tsx
  src/engine/spawn.ts
  src/engine/stream.ts
  src/examples/SimpleStream/SimpleStream.tsx
  src/hooks/index.ts
  src/hooks/useOnce.ts
  src/hooks/useRunStream.ts
  src/hooks/useSpawnEngine.ts
  src/main.tsx
  src/vite-env.d.ts
  vite.config.ts
Labels: must have, scope:core

#26 fix: mustSpawnEngine does not handle browser env correctly
  src/engine/spawn.ts
  src/main.tsx
Labels: bug

#27 chore: set up vitest
  package-lock.json
  package.json
  src/pages/Home/index.test.tsx
  vite.config.ts
Labels: enhancement, must have, scope:core

#37 feat(benchttp): update metric fields
  src/benchttp/common.ts
  src/benchttp/configuration.ts
  src/benchttp/metrics.ts
  src/benchttp/run.ts
  src/components/Typography/core/typography.typings.tsx
  src/examples/inputConfig.ts
  src/typing/array.ts
  src/typing/colors.ts
  src/typing/digit.ts
  src/typing/http.ts
  src/typing/index.ts
Labels: must have, scope:core

#40 chore(benchttp,engine): update after api changes
  src/benchttp/common.ts
  src/benchttp/run.ts
  src/engine/stream.ts
Labels: scope:core

#38 feat: data flow of the run from single component
  src/engine/stream.ts
  src/examples/SimpleStream/SimpleStream.tsx
  src/examples/SimpleStream/components/RunControlPanel.tsx
  src/examples/SimpleStream/components/index.ts
  src/examples/SimpleStream/index.ts
  src/examples/index.ts
  src/hooks/useRunStream.ts
  src/pages/Home/index.test.tsx
  src/pages/Home/index.tsx
  src/pages/Run/components/RunConfigurationPanel.tsx
  src/pages/Run/components/RunResultDisplay.tsx
  src/pages/Run/components/index.ts
  src/pages/Run/index.test.tsx
  src/pages/Run/index.tsx
  src/pages/index.tsx
  src/router/core/router.constants.tsx
Labels: must have, scope:core
