Repository benchttp/desktop, pull requests merged in 2022-10, with the labels that each got.

#55 docs: sidecar ci steps
  README.md
  package.json
Labels: documentation

#54 ci: update submodule and open pr workflow
  .github/workflows/update-egnine.yml
Labels: enhancement

#65 bug: change the fact that the toggle styles were applied to every input
  src/components/Inputs/Toggle/internal/toggle.module.scss
Labels: bug

#68 fix: incorrect update engine job
  .github/workflows/update-engine.yml
Labels: bug

#69 ci: fix gh cli command
  .github/workflows/update-engine.yml
Labels: bug

#74 chore: add styles to input
  src/components/Inputs/SelectInput/SelectInput.tsx
  src/components/Inputs/SelectInput/core/selectInput.helpers.tsx
  src/components/Inputs/SelectInput/index.ts
  src/components/Inputs/SelectInput/internal/SelectInput.helpers.ts
  src/components/Inputs/SelectInput/internal/SelectInput.types.ts
  src/components/Inputs/SelectInput/internal/select-input.module.scss
  src/components/Inputs/TextAreaInput/TextAreaInput.tsx
  src/components/Inputs/TextAreaInput/index.ts
  src/components/Inputs/TextAreaInput/internal/TextAreaInput.helpers.ts
  src/components/Inputs/TextAreaInput/internal/TextAreaInput.types.ts
  src/components/Inputs/TextAreaInput/internal/text-area-input.module.scss
  src/components/Inputs/TextInput/TextInput.tsx
  src/components/Inputs/TextInput/core/textInput.helpers.tsx
  src/components/Inputs/TextInput/index.ts
  src/components/Inputs/TextInput/index.tsx
  src/components/Inputs/TextInput/internal/TextInput.helpers.ts
  src/components/Inputs/TextInput/internal/TextInput.types.ts
  src/components/Inputs/TextInput/internal/text-input.module.scss
  src/components/Inputs/URLInput/URLInput.tsx
  src/components/Tab/core/tab.module.scss
  src/style/mixins/border-bottom.scss
  src/views/Run/internal/Configuration/Configuration.tsx
  src/views/Run/internal/Configuration/HeadersConfiguration/HeadersConfiguration.tsx
Labels: enhancement

#73 feat: stronger config validation
  src/components/Button/Button.tsx
  src/components/Button/core/button.typings.tsx
  src/components/Button/index.ts
  src/components/Button/internal/Button.helpers.ts
  src/components/Button/internal/Button.types.ts
  src/components/Button/internal/button.module.scss
  src/components/Inputs/TextInput/TextInput.tsx
  src/components/Inputs/TextInput/internal/TextInput.types.ts
  src/components/Inputs/URLInput/URLInput.tsx
  src/views/Run/internal/Configuration/Configuration.tsx
  src/views/Run/internal/Configuration/index.tsx
  src/views/Run/internal/Configuration/internal/Configuration.helpers.ts
  src/views/Run/internal/Configuration/internal/HeadersConfiguration/HeadersConfiguration.test.tsx
  src/views/Run/internal/Configuration/internal/HeadersConfiguration/HeadersConfiguration.tsx
  src/views/Run/internal/Configuration/internal/HeadersConfiguration/index.ts
  src/views/Run/internal/Configuration/internal/HeadersConfiguration/internal/HeadersConfiguration.helpers.ts
  src/views/Run/internal/Configuration/internal/HeadersConfiguration/internal/HeadersConfiguration.types.ts
  src/views/Run/internal/Configuration/internal/TestsConfiguration/TestsConfiguration.test.tsx
  src/views/Run/internal/Configuration/internal/TestsConfiguration/TestsConfiguration.tsx
  src/views/Run/internal/Configuration/internal/TestsConfiguration/index.ts
  src/views/Run/internal/Configuration/internal/TestsConfiguration/internal/TestsConfiguration.helpers.ts
  src/views/Run/internal/Configuration/internal/TestsConfiguration/internal/TestsConfiguration.module.scss
  src/views/Run/internal/Configuration/internal/components.ts
Labels: enhancement

#76 feat: improve error handling and display
  src/benchttp/run.ts
  src/components/AppError/AppError.tsx
  src/components/AppError/index.ts
  src/components/index.ts
  src/engine/stream.ts
  src/views/Run/Run.tsx
  src/views/Run/internal/ResultDisplay/ResultDisplay.tsx
  src/views/Run/internal/ResultDisplay/internal/RunErrorDisplay/RunErrorDisplay.tsx
  src/views/Run/internal/ResultDisplay/internal/RunErrorDisplay/index.ts
  src/views/Run/internal/ResultDisplay/internal/StatCard/StatCard.tsx
  src/views/Run/internal/ResultDisplay/internal/StatCard/index.ts
  src/views/Run/internal/ResultDisplay/internal/StatCard/internal/StatCard.helpers.tsx
  src/views/Run/internal/ResultDisplay/internal/StatCard/internal/StatCard.types.ts
  src/views/Run/internal/ResultDisplay/internal/StatCard/internal/stat-card.module.scss
  src/views/Run/internal/ResultDisplay/internal/components.ts
  src/views/Run/internal/Run.helpers.ts
  src/views/UI/index.tsx
Labels: enhancement

#95 feat: add fields tooltip
  src/components/Inputs/TextInput/TextInput.tsx
  src/components/Tooltip/Tooltip.tsx
  src/views/Run/internal/Configuration/internal/TestsConfiguration/internal/SingleTest/SingleTest.tsx
  src/views/UI/UI.tsx
Labels: enhancement

#98 fix: reset state on start new run
  src/views/Run/Run.tsx
  src/views/Run/internal/Run.helpers.ts
Labels: bug

#97 fix: negative timeout
  src/tools/converters.ts
  src/views/Run/internal/ResultDisplay/ResultDisplay.tsx
Labels: bug
